version: '3.7'
services:
  presto-master:
    hostname: presto-master
    image: 'prestosql/presto:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/usr/lib/presto/etc:ro
    networks:
      - presto-network

  hadoop-master:
    hostname: hadoop-master
    image: 'prestodev/hdp2.6-hive:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
    networks:
      - presto-network

  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
#      - './minio/config:/root/.minio'
      - data01:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - presto-network

volumes:
  data01:
    driver: local

networks:
  presto-network:
    driver: bridge
